name: renderer
channels:
  - conda-forge
  - defaults
dependencies:
  # Basic environment setup
  - python=3.10.12
  - pip=24.2
  - pip:
      - pyvista==0.44.2    # PyVista for 3D visualization
      - pyopengl==3.1.6    # OpenGL bindings for Python
      - pandas==2.2.3
      - numpy==2.1.1
      - tqdm==4.67.1
      - natsort==8.4.0

  # VTK for 3D rendering (required by PyVista)
  - vtk=9.3.1             # VTK for 3D rendering (required by PyVista)
